### PR TITLE
Updated with backend api for users

### PR DESCRIPTION
**Pull request by JAGMWPT123**
okay ! I added the api folder in the src folder contains the main files to the project backend,  ..
the I made some changes in the app.jsx and app.css I added functions  for the buttuns and the room panel , you can modify them later as you see fit , 

- to join a room : 
- - press create room 
    . this will generate a code, copy it.
- - then press the join room button
   .  a prompt will ask you to enter the room code , enter the generated code an press ok.
   .  another prompt will ask you to enter the username  , enter it and press ok .
   .  a list will show on the room users panel to show the users in this room .
 -- share the code to a friend and let him follow the same thing,
   . when he enters the room code and his username you too will be in the same room and will show in the panel.
- - when you press disconnect button , you will exit the room and clean up the data.
-

### CODE REVIEW

**Comment by JAGMWPT123** [comment]
this is a basic server , customize the buttons and the panel 
review it and tell me your the new ideas .

**Comment by piyushbaibhav** [comment]
Hey @JAGMWPT123  as I've told you I don't know anything about backed, so should I directly merge your pull request or are there any other things I need to do first?

**Review by piyushbaibhav — APPROVED** [review]

**Comment by piyushbaibhav** [comment]
@JAGMWPT123 could you first sync your beach with the main so there are no conflicts before I merge your branch

**Comment by JAGMWPT123** [comment]
check on vercel how to build and deploy it , or as I see it its already deployed to your vercel account .. check it and feedback me on it .

**Comment by piyushbaibhav** [comment]
Screenshot 2023-12-16 185000

Bro create room isn't working for me. Code is not getting generated.

**Comment by JAGMWPT123** [comment]
would you make me part of the team so I can debuge in vercel as well  .. looks like the socket set up.
image

**Comment by JAGMWPT123** [comment]
image

this on my local machine

**Comment by piyushbaibhav** [comment]
@JAGMWPT123 bro please help me, I don't know where I can add you as a team member.

**Comment by JAGMWPT123** [comment]
Don't worry bro I think I figured it , when I finish with it I will send you the pull request 👍

**Comment by JAGMWPT123** [comment]
@piyushbaibhav okay! turns out vercel doesn't accept websocket"the connection between front-end and back-end" , I tried a lot of methods to make it work but it can't handel it because it was designed for front-end projcets ,, I tried other websites that give such services and I found glitch.com I deployed the typoServer there and it worked fine and made successfull connections.
the thing is the back-end server will close as soon as you close the glitch website ,so to leave it online you may need to pay some fees

**Comment by JAGMWPT123** [comment]
@piyushbaibhav I made a seprated repo for this project https://github.com/JAGMWPT123/typoServer ,I will docment to you how to deploy it in glitch in the readme file there, as soon as I get time ,  then you can fork it.

**Comment by piyushbaibhav** [comment]
Okay @JAGMWPT123

**Pull request closed without merging**
